<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="tvmatp310466m.ad.infosys.com" name="GRP-SI-WF30" tests="2" failures="2" timestamp="21 Jul 2016 09:01:21 GMT" time="63.722" errors="0">
  <testcase name="SI_WF30_CustomListSingleList_CustomCategoryOnLocationsPage_customcategory" time="63.149" classname="com.tests.WorkFlow">
    <failure type="org.openqa.selenium.remote.UnreachableBrowserException" message="Error communicating with the remote browser. It may have died.
Build info: version: &amp;apos;2.51.0&amp;apos;, revision: &amp;apos;1af067d&amp;apos;, time: &amp;apos;2016-02-05 19:15:17&amp;apos;
System info: host: &amp;apos;tvmatp310466m.ad.infosys.com&amp;apos;, ip: &amp;apos;192.168.1.106&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;10.10.5&amp;apos;, java.version: &amp;apos;1.7.0_71&amp;apos;
Driver info: driver.version: AppiumDriver
Session ID: 1847e52d-f7e9-442c-9e53-d5427a78217a
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1115fbeb54402003, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]">
      <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp310466m.ad.infosys.com', ip: '192.168.1.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_71'
Driver info: driver.version: AppiumDriver
Session ID: 1847e52d-f7e9-442c-9e53-d5427a78217a
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1115fbeb54402003, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:529)
	at com.components.pages.InventoryToolPage.InvTools_SetUpInventory(InventoryToolPage.java:85)
	at com.tests.WorkFlow.SI_WF30_CustomListSingleList_CustomCategoryOnLocationsPage_customcategory(WorkFlow.java:1361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.104.8:4723 [/10.155.104.8] failed: Connection refused
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp310466m.ad.infosys.com', ip: '192.168.1.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_71'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 30 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.104.8:4723 [/10.155.104.8] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:52)
	... 31 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 44 more
]]>
    </failure>
  </testcase> <!-- SI_WF30_CustomListSingleList_CustomCategoryOnLocationsPage_customcategory -->
  <testcase name="SI_WF30_CustomListSingleList_CustomCategoryOnLocationsPage_customcategory" time="63.654" classname="com.tests.WorkFlow">
    <failure type="java.lang.RuntimeException" message="Error occured while closing webdriver sessionError communicating with the remote browser. It may have died.
Build info: version: &amp;apos;2.51.0&amp;apos;, revision: &amp;apos;1af067d&amp;apos;, time: &amp;apos;2016-02-05 19:15:17&amp;apos;
System info: host: &amp;apos;tvmatp310466m.ad.infosys.com&amp;apos;, ip: &amp;apos;192.168.1.106&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;10.10.5&amp;apos;, java.version: &amp;apos;1.7.0_71&amp;apos;
Driver info: driver.version: RemoteWebDriver
Session ID: 1847e52d-f7e9-442c-9e53-d5427a78217a
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1115fbeb54402003, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]">
      <![CDATA[java.lang.RuntimeException: Error occured while closing webdriver sessionError communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp310466m.ad.infosys.com', ip: '192.168.1.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_71'
Driver info: driver.version: RemoteWebDriver
Session ID: 1847e52d-f7e9-442c-9e53-d5427a78217a
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1115fbeb54402003, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at zRfghY.s.b(WebDriverFactory.java:48)
	at com.iwaf.framework.testng.TestNGTestListener.closeTestSession(TestNGTestListener.java:458)
	at com.iwaf.framework.testng.TestNGTestListener.onTestFailure(TestNGTestListener.java:291)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1693)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1677)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp310466m.ad.infosys.com', ip: '192.168.1.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_71'
Driver info: driver.version: RemoteWebDriver
Session ID: 1847e52d-f7e9-442c-9e53-d5427a78217a
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jinita_jose/Desktop/Sysco/APKs/July14/UOMQA_SQ-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1115fbeb54402003, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:189)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526)
	at zRfghY.t.c(WebDriverInstanceGenerator.java:131)
	at zRfghY.s.b(WebDriverFactory.java:45)
	... 23 more
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.104.8:4723 [/10.155.104.8] failed: Connection refused
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp310466m.ad.infosys.com', ip: '192.168.1.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_71'
Driver info: driver.version: RemoteWebDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 28 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.104.8:4723 [/10.155.104.8] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:52)
	... 29 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 42 more
]]>
    </failure>
  </testcase> <!-- SI_WF30_CustomListSingleList_CustomCategoryOnLocationsPage_customcategory -->
</testsuite> <!-- GRP-SI-WF30 -->
